import { MaterialProperty } from "../../types/material";

export const MATERIAL_PRESETS: Record<string, MaterialProperty> = {
    silk: {
        id: "silk",
        name: "Mulberry Silk",
        category: "Natural",
        description: "Ultra-fine protein filament fabric with gossamer drape and liquid fluidity.",
        density: 0.065,
        stretchCompliance: 0.0001,
        bendCompliance: 0.015,
        damping: 0.012,
        friction: 0.15,
        thicknessMm: 0.12,
        color: [0.35, 0.78, 0.85],
        roughness: 0.25,
        stiffnessRating: "Very Low",
        stretchRating: "Very Low",
        weightRating: "Ultra Light",
    },
    cotton: {
        id: "cotton",
        name: "Organic Cotton",
        category: "Natural",
        description: "Versatile woven cellulose fiber with natural softness and moderate body.",
        density: 0.180,
        stretchCompliance: 0.0005,
        bendCompliance: 0.120,
        damping: 0.025,
        friction: 0.40,
        thicknessMm: 0.35,
        color: [0.88, 0.86, 0.82],
        roughness: 0.70,
        stiffnessRating: "Low",
        stretchRating: "Low",
        weightRating: "Light",
    },
    denim: {
        id: "denim",
        name: "Raw Denim (14oz)",
        category: "Heavy",
        description: "Heavyweight twill weave with rigid warp tension and sharp structural folds.",
        density: 0.450,
        stretchCompliance: 0.00002,
        bendCompliance: 0.650,
        damping: 0.050,
        friction: 0.65,
        thicknessMm: 0.85,
        color: [0.18, 0.28, 0.52],
        roughness: 0.85,
        stiffnessRating: "High",
        stretchRating: "Very Low",
        weightRating: "Heavy",
    },
    linen: {
        id: "linen",
        name: "Belgian Linen",
        category: "Natural",
        description: "Crisp flax fiber fabric with distinctive angular drape and dry tactile hand.",
        density: 0.230,
        stretchCompliance: 0.00008,
        bendCompliance: 0.380,
        damping: 0.030,
        friction: 0.45,
        thicknessMm: 0.40,
        color: [0.78, 0.72, 0.62],
        roughness: 0.60,
        stiffnessRating: "Medium",
        stretchRating: "Very Low",
        weightRating: "Medium",
    },
    leather: {
        id: "leather",
        name: "Tanned Calfskin",
        category: "Heavy",
        description: "Dense full-grain leather displaying profound bending resistance and dampening.",
        density: 0.780,
        stretchCompliance: 0.00001,
        bendCompliance: 0.880,
        damping: 0.080,
        friction: 0.75,
        thicknessMm: 1.40,
        color: [0.45, 0.24, 0.14],
        roughness: 0.50,
        stiffnessRating: "Rigid",
        stretchRating: "Very Low",
        weightRating: "Heavy",
    },
    rubber: {
        id: "rubber",
        name: "Natural Latex Rubber",
        category: "Technical",
        description: "Hyper-elastic isotropic elastomer membrane with high stretch compliance.",
        density: 0.850,
        stretchCompliance: 0.045,
        bendCompliance: 0.060,
        damping: 0.070,
        friction: 0.90,
        thicknessMm: 0.60,
        color: [0.15, 0.15, 0.18],
        roughness: 0.30,
        stiffnessRating: "Low",
        stretchRating: "Elastic",
        weightRating: "Heavy",
    },
    wool: {
        id: "wool",
        name: "Merino Flannel Wool",
        category: "Natural",
        description: "Lofty crimped animal fiber with generous air permeability and plush rolling drape.",
        density: 0.360,
        stretchCompliance: 0.002,
        bendCompliance: 0.180,
        damping: 0.045,
        friction: 0.55,
        thicknessMm: 0.75,
        color: [0.48, 0.18, 0.22],
        roughness: 0.90,
        stiffnessRating: "Low",
        stretchRating: "Medium",
        weightRating: "Medium",
    },
    canvas: {
        id: "canvas",
        name: "Sailcloth Duck Canvas",
        category: "Technical",
        description: "Tightly woven plain-weave canvas engineered for high tensile resilience.",
        density: 0.540,
        stretchCompliance: 0.00003,
        bendCompliance: 0.720,
        damping: 0.040,
        friction: 0.60,
        thicknessMm: 0.95,
        color: [0.72, 0.68, 0.56],
        roughness: 0.80,
        stiffnessRating: "High",
        stretchRating: "Very Low",
        weightRating: "Heavy",
    },
};

export const DEFAULT_MATERIAL = MATERIAL_PRESETS.silk;
